### ISSUE TITLE
Can't 'make book' on Ubuntu 18.04

### ISSUE THREAD

**Issue by sebastian-burlacu** [MartinMSPedersen/Crafty-Chess#1]
Hi Martin,

I realize this isn't your code but you might be able to help since the official documentation is barren of mentions of how to compile book.bin.

Included in the source code is a book.c file. Is this to compile and output a 'book' executable file which is then used to make books.bin from the .pgn file? If so, first, I had to edit book.c and chess.h to insert a '#define UNIX' so that it wouldn't keep trying to load 'windows.h'. Second, I got these errors:

# make book          
cc     book.c   -o book                                   
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'                     
/tmp/ccqptcMM.o: In function `Book':                            
book.c:(.text+0x70): undefined reference to `moves_out_of_book'
book.c:(.text+0xa5): undefined reference to `books_file'            
book.c:(.text+0xc1): undefined reference to `books_file'        
book.c:(.text+0xd8): undefined reference to `books_file'      

Any ideas? I'm just trying to run crafty chess as a benchmarking tool, and want to give it some books to process and see how long it takes.

Thanks for any insight you can provide.

**Comment by MartinMSPedersen** [comment]
> I realize this isn't your code but you might be able to help

Sure.  I know many details of the code and how to use the binary. I have been using crafty a lot to annotate my games in the past.

> Included in the source code is a book.c file. Is this to compile and output a 'book' executable file which is then used to make books.bin from the .pgn file?

Nope. The code is only meant to produce a single binary. 
The way to generate the book-files is described here: [craftydoc.html](http://craftychess.com/documentation/craftydoc.html#Opening%20Book)

Feel free to write to me again if you need more help.

**Comment by MartinMSPedersen** [comment]
> Included in the source code is a book.c file. Is this to compile and output a 'book' executable file which is then used to make books.bin from the .pgn file? If so, first, I had to edit book.c and chess.h to insert a '#define UNIX' so that it wouldn't keep trying to load 'windows.h'. Second, I got these errors:

The way to compile the code is just
`make unix-gcc`

**Comment by MartinMSPedersen** [comment]
Solved
